services:
  web:
    image: php:8.1-apache
    container_name: megared_web
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www/html
    environment:
      - DB_HOST=b1fwlu040o0pjurosjp8-mysql.services.clever-cloud.com
      - DB_NAME=b1fwlu040o0pjurosjp8
      - DB_USER=ulhihvey1k4zyr7c
      - DB_PASS=EGTPk59A6nOPISub1yC4
      - DB_PORT=3306
    command: >
      bash -c "apt-get update && apt-get install -y libpng-dev zlib1g-dev libzip-dev && 
      docker-php-ext-install pdo pdo_mysql mysqli gd zip && 
      a2enmod rewrite && 
      apache2-foreground"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: megared_phpmyadmin
    ports:
      - "8081:80"
    environment:
      - PMA_HOST=b1fwlu040o0pjurosjp8-mysql.services.clever-cloud.com
      - PMA_PORT=3306
      - PMA_USER=ulhihvey1k4zyr7c
      - PMA_PASSWORD=EGTPk59A6nOPISub1yC4