services:
  web:
    image: php:8.1-apache
    container_name: megared_web
    ports:
      - "${WEB_PORT}:80"
    volumes:
      - ./src:/var/www/html
    environment:
      - DB_HOST=${DB_HOST}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - DB_PORT=${DB_PORT}
      - APP_URL=${APP_URL}
    command: >
      bash -c "apt-get update && apt-get install -y libpng-dev zlib1g-dev libzip-dev && 
      docker-php-ext-install pdo pdo_mysql mysqli gd zip && 
      a2enmod rewrite && 
      apache2-foreground"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: megared_phpmyadmin
    ports:
      - "${PHPMYADMIN_PORT}:80"
    environment:
      - PMA_HOST=${DB_HOST}
      - PMA_PORT=${DB_PORT}
      - PMA_USER=${DB_USER}
      - PMA_PASSWORD=${DB_PASS}